service: aws-python-sample

provider:
  name: aws
  runtime: python3.6
  environment:
    DYNAMO_USERS_TABLE: users
    DYNAMO_REGION: us-west-2

plugins:
  - serverless-offline

functions:
  hello:
    handler: calendly/events/service_router.main
    events:
      - http:
          method: GET
          path: /user
      - http:
          method: POST
          path: /user